apiVersion: apps/v1
kind: Deployment
metadata:
  name: praktikan3-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: praktikan3-flask
  template:
    metadata:
      labels:
        app: praktikan3-flask
    spec:
      containers:
        - name: praktikan3-flask
          image: mwlanaz/praktikan3-flask:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: praktikan3-flask
spec:
  type: NodePort
  selector:
    app: praktikan3-flask
  ports:
    - port: 5000
      targetPort: 5000
