---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: praktikan1-apache2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: mwlanaz/apache
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: praktikan1-apache2
spec:
  selector:
    app: apache
  ports:
    - port: 80
      targetPort: 80
